package db;

import models.Article;
import models.Category;
import models.Journalist;

import java.util.Date;

public class Seeds {

    public static void seedData() {
        Date date1 = new Date(118, 07, 17);
        Date date2 = new Date(118, 07, 18);
        Date date3 = new Date(118, 07, 17);
        Date date4 = new Date(118, 07, 16);
        Date date5 = new Date(118, 07, 19);
        Date date6 = new Date(118, 07, 20);
        Date date7 = new Date(118, 07, 18);
        Date date8 = new Date(118, 07, 15);
        Journalist journalist1 = new Journalist("Dave Cornelius", "Dave Cornelius is a made up journalist", "@DCornelius", "images/DaveCornelius.jpg");
        Journalist journalist2 = new Journalist("Spider Jerusalem", "Spider Jerusalem is a figment of Warren Ellis' Imagination", "@SJerusalem", "images/SpiderJerusalem.jpg");
        DBHelper.save(journalist1);
        DBHelper.save(journalist2);

        Article article1 = new Article("How I Improved Cloud Computing In 2 Days", "Long-term brands are becoming immersive organic growth experts. Our market focus development lifecycle enables corporate, unparalleled core assets. So we can hit the ground running, we will be strategically calibrating every vertical in our space. Change the way you do business - adopt seamless prince2 practitioners.", date1, "Is your industry leader prepared for long-term executive search growth? Key players will take ownership of their capabilities by reliably strategizing best-in-class emerging markets. Key players will take ownership of their market foci by strategically right-sizing innovative bandwidths. We thrive because of our seamless core competency and corporate visibility culture.</p><p>We aim to intelligently align our big data by virtually growing our company-wide mission critical brands. Key players will take ownership of their action points by iteratively relaying customer-focused stand-ups. Our Value-Added Vertical solution offers standpoints a suite of next-generation offerings. We use our immersive dot-bombs to ethically manage our agile workflow expectations.\n" +
                "\n", journalist1, "images/image1.jpg", Category.POLITICS);


        Article article2 = new Article("5 Romantic Blockchain Ideas", "Company-wide game changers intelligently enable actionable big datas for our industry leaders. Our capability development lifecycle enables end-to-end, senior drivers. We aim to conservatively grow our core competency by reliably right-sizing our next-generation proactive bandwidths. We use our best-of-breed low hanging fruit to globally manage our agile workflow expectations.", date2, "In the future, will you be able to dynamically synergise innovations in your business? Value-added capabilities are becoming best-in-class team player experts. In the future, will you be able to reliably leverage game changers in your business? We aim to virtually align our step-change by effectively connecting our corporate world-class stakeholders.</p><p>Change the way you do business - adopt long-term action points. Going forward, our mobile organic growth will deliver value to industry leaders. In the synergy space, industry is iteratively integrating its innovative milestones. Change the way you do business - adopt knowledge transfer enterprises.</p><p>Next-generation user experiences proactively enable seamless architectures for our siloes. You need to conservatively incentivize your executive searches to increase your stand-up velocity. Our business monetizes verticals to ethically and intelligently impact our competitive core competency. Our prince2 practitioner development lifecycle enables wholesale, company-wide standard setters.", journalist2, "images/image2.jpg", Category.SCIENCE);

        Article article3 = new Article("The Worst Advice We've Ever Heard About Agile Workflow","Our Value-Added Best Practice solution offers standpoints a suite of mission critical offerings. Best-in-class core assets virtually enable corporate bandwidths for our siloes. Efficiencies will come from reliably relaying our diversities. So we can hit the ground running, we will be effectively offshoring every paradigm shift in our space.", date3, "We thrive because of our unparalleled step-change and customer-focused action point culture. Is your enterprise prepared for world-class low hanging fruit growth? In the future, will you be able to conservatively integrate industry leaders in your business? We use our immersive user experiences to globally manage our team player expectations.</p><p>Our best practice development lifecycle enables competitive, wholesale platforms. Going forward, our proactive vertical will deliver value to game changers. You need to iteratively engineer your milestones to increase your dot-bomb velocity. Our Corporate Market Focus solution offers innovations a suite of mission critical offerings.</p><p>So we can hit the ground running, we will be strategically right-sizing every stakeholder in our space. We thrive because of our next-generation stack and best-in-class capability culture. Our business leverages deliverables to ethically and intelligently relay our company-wide visibility. Actionable standpoints are becoming long-term architecture experts.</p><p>Key players will take ownership of their enterprises by effectively growing end-to-end drivers. So we can hit the ground running, we will be dynamically connecting every bandwidth in our space. Proactively synergising reliably knowledge transfer agile workflows is crucial to our best-of-breed brand. It's critical that we give 110% when virtually offshoring emerging markets.", journalist1, "images/image3.jpg", Category.UK);

        Article article4 = new Article("Signs You Should Invest In Organic Growth","Wholesale dot-bombs dynamically enable proactive innovations for our propositions. Efficiencies will come from proactively synergising our visibilities. Key players will take ownership of their alignments by iteratively impacting immersive low hanging fruit. Change the way you do business - adopt mobile stand-ups.", date4, "We use our next-generation bandwidths to strategically manage our platform expectations. Intelligently leveraging dynamically customer-focused emerging markets is crucial to our innovative capability. In the future, will you be able to virtually synergise market foci in your business? In the future, will you be able to reliably integrate siloes in your business?</p><p>Effectively impacting iteratively long-term milestones is crucial to our immersive driver. Efficiencies will come from globally investing our stakeholders. We aim to proactively revolutionize our best practice by ethically incentivizing our senior mobile clouds. Is your team player prepared for proactive dot-bomb growth?</p><p>We thrive because of our seamless proposition and wholesale executive search culture. Efficiencies will come from conservatively strategizing our architectures. We use our holistic industry leaders to globally manage our brand expectations. Our business engineers action points to effectively and iteratively deep-dive our world-class prince2 practitioner.", journalist2, "images/image4.jpg", Category.SCIENCE);

        Article article5 = new Article("The History Of User Experience","So we can hit the ground running, we will be globally revolutionizing every prince2 practitioner in our space. Best-of-breed core competencies ethically enable knowledge transfer ballpark figures for our capabilities. Change the way you do business - adopt innovative milestones. Our emerging market development lifecycle enables holistic, seamless big datas.", date5, "You need to reliably leverage your market foci to increase your milestone velocity. You need to iteratively connect your enterprises to increase your user experience velocity. Competitive standpoints virtually enable customer-focused core competencies for our architectures. We aim to proactively engineer our driver by intelligently integrating our immersive mobile stand-ups.</p><p>Conservatively touching base about reusing emerging markets will make us leaders in the best-in-class team player industry. We use our best-of-breed propositions to globally manage our silo expectations. In the big data space, industry is dynamically revolutionizing its innovative action points. We thrive because of our mission critical innovation and holistic best practice culture.</p><p>You need to ethically virtualise your low hanging fruit to increase your alignment velocity. Is your capability prepared for long-term game changer growth? Efficiencies will come from effectively growing our core assets. Proactive prince2 practitioners are becoming wholesale platform experts.", journalist2, "images/image5.jpg", Category.SPORTS);

        Article article6 = new Article("What Will Paradigm Shifts Be Like In 100 Years?","So we can hit the ground running, we will be conservatively engineering every deliverable in our space. Going forward, our competitive action point will deliver value to stacks. We thrive because of our end-to-end stakeholder and unparalleled synergy culture. Key players will take ownership of their game changers by intelligently right-sizing actionable architectures.", date6, "It's critical that we give 110% when iteratively aligning milestones. Is your capability prepared for company-wide action point growth? Virtually incentivizing strategically knowledge transfer enterprises is crucial to our wholesale visibility. We aim to ethically transform our standard setter by globally revolutionizing our end-to-end customer-focused executive searches.</p><p>Senior dot-bombs are becoming long-term agile workflow experts. We thrive because of our best-in-class emerging market and holistic stack culture. Effectively engineering conservatively immersive clouds is crucial to our seamless stand-up. Proactive architectures are becoming unparalleled proposition experts.</p><p>In the future, will you be able to reliably impact enterprises in your business? Our low hanging fruit development lifecycle enables actionable, world-class paradigm shifts. So we can hit the ground running, we will be intelligently integrating every core competency in our space. You need to dynamically connect your prince2 practitioners to increase your silo velocity.", journalist1, "images/image6.jpg", Category.POLITICS);

        Article article7 = new Article("How To Solve The Biggest Problems With Big Data","Change the way you do business - adopt next-generation clouds. Our World-Class Agile Workflow solution offers enterprises a suite of company-wide offerings. Is your executive search prepared for customer-focused industry leader growth? Going forward, our long-term vertical will deliver value to step-changes.", date7, "Actionable game changers proactively enable proactive team players for our enterprises. Intelligently investing strategically knowledge transfer industry leaders is crucial to our company-wide paradigm shift. We aim to globally impact our capability by ethically facilitating our innovative customer-focused clouds. Change the way you do business - adopt best-in-class bandwidths.</p><p>We use our seamless user experiences to reliably manage our milestone expectations. You need to dynamically virtualise your verticals to increase your enterprise velocity. Efficiencies will come from virtually reusing our architectures. Our Immersive Deliverable solution offers stand-ups a suite of wholesale offerings.</p><p>Our Value-Added Step-Change solution offers diversities a suite of unparalleled offerings. We use our end-to-end dot-bombs to iteratively manage our visibility expectations. Long-term agile workflows are becoming mission critical stack experts. Best-of-breed core competencies conservatively enable holistic siloes for our standpoints.", journalist2, "images/image7.jpg", Category.WORLD);

        Article article8 = new Article("20 Myths About Emerging Market Architecture","In the user experience space, industry is strategically reusing its senior enterprises. Iteratively touching base about leveraging drivers will make us leaders in the best-in-class standard setter industry. Effectively growing dynamically wholesale team players is crucial to our best-of-breed organic growth. Seamless platforms are becoming proactive capability experts.", date8, "Our vertical development lifecycle enables best-of-breed, long-term low hanging fruit. Our business synergises paradigm shifts to proactively and virtually align our holistic organic growth. Efficiencies will come from ethically facilitating our deliverables. We aim to iteratively incentivize our capability by strategically reusing our seamless senior clouds.</p><p>Our business monetizes visibilities to reliably and intelligently strategize our innovative silo. Change the way you do business - adopt world-class executive searches. In the future, will you be able to dynamically right-size milestones in your business? We aim to effectively connect our standard setter by globally offshoring our proactive value-added enterprises.</p><p>Our business deep-dives enterprises to conservatively and globally integrate our knowledge transfer agile workflow. In the future, will you be able to effectively impact diversities in your business? Intelligently virtualising dynamically best-in-class ballpark figures is crucial to our mobile standpoint. Customer-focused synergies reliably enable mission critical alignments for our stand-ups.", journalist1, "images/image8.jpg", Category.WORLD);

        DBHelper.save(article1);
        DBHelper.save(article2);
        DBHelper.save(article3);
        DBHelper.save(article4);
        DBHelper.save(article5);
        DBHelper.save(article6);
        DBHelper.save(article7);
        DBHelper.save(article8);
    }
}